[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Supabase config
  NEXT_PUBLIC_SUPABASE_URL = "https://bxiieunzrcdbxqadapcl.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4aWlldW56cmNkYnhxYWRhcGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTAzMTIsImV4cCI6MjA2NDQ2NjMxMn0.87x8KfKhfQoJlmbBg1I1zHwEMIE-Uvk-THCFmEn-n6E"
  
  # API keys
  GEMINI_API_KEY = "AIzaSyAnota1ZAmXv3LoAfmI0J5VQarPv4qMTMA"
  
  # Stripe config
  STRIPE_SECRET_KEY = "sk_test_your_key"
  STRIPE_WEBHOOK_SECRET = "whsec_your_key"
  STRIPE_PRICE_ID = "price_your_id"
  
  # Environment - using Netlify's URL automatically
  RUNTIME_ENV = "production"
  NEXT_PUBLIC_APP_URL = "https://docmagic1.netlify.app"
  
  # Performance tuning
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle all routes properly for Next.js
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server-edge/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server-edge"
  status = 200
  force = true

# Add CORS headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Function configuration
[functions]
  directory = ".next/server"  # Points to Next.js server functions
  node_bundler = "esbuild"
  timeout = 30  # Increased timeout for API routes